### ISSUE TITLE
Workflow not connecting to PIA app

### ISSUE THREAD

**Issue by skotzko** [skonagaya/PIA-Interface#2]
When I run `pia start` from Alfred, the workflow is unable to connect to the PIA app. This is the error notification:
![screen shot 2018-01-03 at 1 24 37 pm](https://user-images.githubusercontent.com/311226/34540607-0ecc9f44-f08a-11e7-8568-20211e2be39e.png)

Once I started getting this issue, I re-installed the latest PIA client from the website, which didn't fix it.

Running v75 of the PIA app on macOS High Sierra 10.13.2.

**Comment by skonagaya** [comment]
Workflow has been updated to support v75.

**Comment by skotzko** [comment]
Verified it worked once I downloaded new workflow. Thanks! Dunno if you have it on Packal.org but may also be useful to update there so workflow can be updated right from Alfred launcher.

**Comment by skonagaya** [comment]
I'll look into it. Thanks for the insight!
